# Default values for random.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: elf159/converter #поставь сюда свой образ
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""

service:
  port: 8080

fullnameOverride: ""

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 35
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 40
  periodSeconds: 20

extraEnv: {}
