spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        driverClassName: org.postgresql.Driver
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update
logging:
  level:
    com:
      example:
        accounts: DEBUG
grpc:
  client:
    grpcClient:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      address: ${CONVERTER_URL}
      negotiation-type: plaintext

